jobs:
  - name: dv-man11
    type: manifest
    steps:
      - IN: pipelines-sample1
        pull: true
        
  - name: dv-man11-pvt
    type: manifest
    steps:
      - IN: dv-imgtest7
        pull: false
        
  - name: dv-man12
    type: manifest
    steps:
      - IN: dv-imgtest6
        pull: true
