jobs:
  - name: job-manifest1
    type: manifest
    steps:
      - IN: pipelines-sample-do1
        pull: true
      - IN: pipelines-sample1-dv-opts
        
  - name: job-manifest2
    type: manifest
    steps:
      - IN: pipelines-sample1-do2
        pull: false
      - IN: pipelines-sample1-dv-opts
      
  - name: job-ddc-deploy1
    type: deploy
    steps:
      - IN: job-manifest2
      - IN: pipelines-sample1-ddc-cluster
      

        
